-- SQL Server: bảng lưu token reset mật khẩu
CREATE TABLE RESET_PASSWORD_TOKEN (
    Id BIGINT IDENTITY(1,1) PRIMARY KEY,
    Token NVARCHAR(64) NOT NULL UNIQUE,
    TaiKhoanId INT NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    Used BIT NOT NULL DEFAULT 0,
    UsedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_RESET_PASSWORD_TOKEN_TAIKHOAN FOREIGN KEY (TaiKhoanId)
        REFERENCES TAI_KHOAN(Id)
);

CREATE INDEX IX_RESET_PASSWORD_TOKEN_TAIKHOAN
ON RESET_PASSWORD_TOKEN(TaiKhoanId);
