-- Chuẩn hóa RBAC: ADMIN / STAFF / CUSTOMER
-- SQL Server

-- Đổi USER -> CUSTOMER nếu CUSTOMER chưa tồn tại
IF EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'USER')
    AND NOT EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'CUSTOMER')
BEGIN
    UPDATE VAI_TRO
    SET Ma = 'CUSTOMER', Ten = N'Khách hàng'
    WHERE Ma = 'USER';
END

-- Đổi NHAN_VIEN -> STAFF nếu STAFF chưa tồn tại
IF EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'NHAN_VIEN')
    AND NOT EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'STAFF')
BEGIN
    UPDATE VAI_TRO
    SET Ma = 'STAFF', Ten = N'Nhân viên'
    WHERE Ma = 'NHAN_VIEN';
END

-- Nếu cả USER và CUSTOMER cùng tồn tại, gộp USER vào CUSTOMER
IF EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'USER')
    AND EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'CUSTOMER')
BEGIN
    DECLARE @OldUserId INT = (SELECT TOP 1 Id FROM VAI_TRO WHERE Ma = 'USER');
    DECLARE @CustomerId INT = (SELECT TOP 1 Id FROM VAI_TRO WHERE Ma = 'CUSTOMER');

    INSERT INTO TAI_KHOAN_VAI_TRO (TaiKhoanId, VaiTroId)
    SELECT TaiKhoanId, @CustomerId
    FROM TAI_KHOAN_VAI_TRO
    WHERE VaiTroId = @OldUserId
      AND NOT EXISTS (
          SELECT 1 FROM TAI_KHOAN_VAI_TRO t2
          WHERE t2.TaiKhoanId = TAI_KHOAN_VAI_TRO.TaiKhoanId
            AND t2.VaiTroId = @CustomerId
      );

    DELETE FROM TAI_KHOAN_VAI_TRO WHERE VaiTroId = @OldUserId;
    DELETE FROM VAI_TRO WHERE Id = @OldUserId;
END

-- Nếu cả NHAN_VIEN và STAFF cùng tồn tại, gộp NHAN_VIEN vào STAFF
IF EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'NHAN_VIEN')
    AND EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'STAFF')
BEGIN
    DECLARE @OldStaffId INT = (SELECT TOP 1 Id FROM VAI_TRO WHERE Ma = 'NHAN_VIEN');
    DECLARE @StaffId INT = (SELECT TOP 1 Id FROM VAI_TRO WHERE Ma = 'STAFF');

    INSERT INTO TAI_KHOAN_VAI_TRO (TaiKhoanId, VaiTroId)
    SELECT TaiKhoanId, @StaffId
    FROM TAI_KHOAN_VAI_TRO
    WHERE VaiTroId = @OldStaffId
      AND NOT EXISTS (
          SELECT 1 FROM TAI_KHOAN_VAI_TRO t2
          WHERE t2.TaiKhoanId = TAI_KHOAN_VAI_TRO.TaiKhoanId
            AND t2.VaiTroId = @StaffId
      );

    DELETE FROM TAI_KHOAN_VAI_TRO WHERE VaiTroId = @OldStaffId;
    DELETE FROM VAI_TRO WHERE Id = @OldStaffId;
END

-- Đảm bảo có đủ 3 vai trò chuẩn
IF NOT EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'ADMIN')
    INSERT INTO VAI_TRO(Ma, Ten) VALUES('ADMIN', N'Quản trị viên');

IF NOT EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'STAFF')
    INSERT INTO VAI_TRO(Ma, Ten) VALUES('STAFF', N'Nhân viên');

IF NOT EXISTS (SELECT 1 FROM VAI_TRO WHERE Ma = 'CUSTOMER')
    INSERT INTO VAI_TRO(Ma, Ten) VALUES('CUSTOMER', N'Khách hàng');

-- UNIQUE (TaiKhoanId, VaiTroId)
IF NOT EXISTS (
    SELECT 1 FROM sys.indexes
    WHERE name = 'UQ_TAI_KHOAN_VAI_TRO'
      AND object_id = OBJECT_ID('TAI_KHOAN_VAI_TRO')
)
BEGIN
    ALTER TABLE TAI_KHOAN_VAI_TRO
    ADD CONSTRAINT UQ_TAI_KHOAN_VAI_TRO UNIQUE (TaiKhoanId, VaiTroId);
END
